# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build-and-test:
    docker:
      - image: error23/circle-ci-builder:3.1

    steps:

      # Checkout git project
      - checkout

      - run:
          name: Calculating dependencies cache key
          command: find -name "build.gradle" -o -name "gradle.properties" | xargs cat | md5sum | cut -d' ' -f1 > /tmp/build_gradle_md5

        # Restore gradle dependencies cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "/tmp/build_gradle_md5" }}
            - v1-dependencies-

      # Build gradle
      - run:
          name: Build
          command: |
            if [ -z "${CIRCLE_TAG}" ]; then
              ./gradlew clean build
            else
              ./gradlew clean build -P version=`echo ${CIRCLE_TAG} | tr -d 'releases/'`
            fi

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/build/test-results/test/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always

      - store_test_results:
          path: ~/test-results

      - run:
          name: Save artifacts
          command: |
            mkdir ~/artifacts
            find . -type f -regex ".*/build/libs/.*jar" -exec cp {} ~/artifacts/ \;

      - store_artifacts:
          path: ~/artifacts
          destination: bin/

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "/tmp/build_gradle_md5" }}

      # Persist built project to workspace
      - persist_to_workspace:
          root: /
          paths:
            - root

  release:
    docker:
      - image: error23/circle-ci-builder:3.1

    steps:

      # Attach built workspace
      - attach_workspace:
          at: /

      # Publish gradle plugins
      - run:
          name: Publish gradle plugins
          command: ./gradlew publish -P version=`echo ${CIRCLE_TAG} | tr -d 'releases/'`

workflows:
  version: 2
  build_and_release:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /.*/
      - release:
          requires:
            - build-and-test
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
